services:
  - type: web
    name: soundoff-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SOUNDCLOUD_CLIENT_ID
        sync: false
      - key: SETLIST_FM_API_KEY
        sync: false
      - key: SETLISTFM_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1 